app/controllers/C_IA_Trainer.py
import os
from flask import Blueprint, Response, render_template, json, jsonify
from flask import current_app as app
import cv2
import dlib
import numpy as np
from app.controllers.C_People import C_People
from app.forms.F_Trainer import F_Trainer
from app.models.Models import People
from sklearn import preprocessing
from sklearn import svm
from sklearn.model_selection import train_test_split
import joblib

from app.utils.utils import check_role
class CustomSVM:
    def __init__(self):
        self.model = svm.SVC(kernel='linear')
        self.le = preprocessing.LabelEncoder()

    def train(self, X, y):
        y_encoded = self.le.fit_transform(y)

        if len(np.unique(y_encoded)) < 2:
            print("Menos de dos clases, no se puede dividir el conjunto de datos.")
            self.model.fit(X, y_encoded)
        else:
            X_train, X_test, y_train, y_test = train_test_split(
                X, y_encoded, test_size=0.2, random_state=42)

            self.model.fit(X_train, y_train)
            accuracy = self.model.score(X_test, y_test)
            print(f'Accuracy: {accuracy}')

    def save_model(self, file_path):
        joblib.dump({'model': self.model, 'le': self.le}, file_path)

    def load_model(self, file_path):
        data = joblib.load(file_path)
        self.model = data['model']
        self.le = data['le']

    def predict(self, img):
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (64, 64))
        img = img.astype(np.float32) / 255.0
        img = img.reshape(-1, 64 * 64 * 3)
        prediction = self.model.predict(img)
        predicted_label = self.le.inverse_transform(prediction)[0]

        return predicted_label

class C_IA_Trainer():
    ia = Blueprint('ia', __name__)
    
    @ia.route('/identify', methods=['POST'])
    @check_role(['ADMINISTRADOR', 'MEDICO', 'FARMACEUTICO'])
    def identify():
        message = {"correcto": '', "alerta": '', "error": ''}
        try:
            prediction = C_IA_Trainer.identify_person()
            person_data = People.query.filter_by(peop_dni=prediction).first()

            if person_data is not None:
                message['correcto'] = "La persona identificada mediante la cámara es {}".format(
                    person_data.peop_names+' '+person_data.peop_lastnames)
                message['cod'] = person_data.peop_id
                message['name'] = person_data.peop_names+' ' + \
                    person_data.peop_lastnames
                message['dni'] = person_data.peop_dni
                message['age'] = C_People.calcular_edad(
                    person_data.peop_birthdate)
                message['birthdate'] = person_data.peop_birthdate.strftime("%d/%m/%Y")
                message['gender'] = "MASCULINO" if person_data.peop_gender == 'M' else 'FEMENINO'
            else:
                message['alerta'] = prediction

        except Exception as e:
            message['error'] = str(e)

        return jsonify(message)


    def identify_person():
        face_detector = dlib.get_frontal_face_detector()
        predictor = dlib.shape_predictor(
            "shape_predictor_68_face_landmarks.dat")
        cap = cv2.VideoCapture(0)

        try:
            _, webcam_img = cap.read()

            gray_webcam_img = cv2.cvtColor(webcam_img, cv2.COLOR_BGR2GRAY)
            faces = face_detector(gray_webcam_img)

            if not faces:
                return "No se detectaron caras frente a la cámara"

            face = faces[0]
            shape = predictor(gray_webcam_img, face)

            x, y, w, h = shape.rect.left() - 15, shape.rect.top() - 15, shape.rect.width() + 30, shape.rect.height() + 30
            x, y = max(x, 0), max(y, 0)

            cropped_webcam_img = webcam_img[y:y+h, x:x+w]

            custom_svm = CustomSVM()
            custom_svm.load_model('model_weights.joblib')

            prediction = custom_svm.predict(cropped_webcam_img)

            if prediction == "unknown":
                return "Persona desconocida"

            return prediction
        except Exception as e:
            raise RuntimeError(f"Error al capturar la imagen de la webcam: {e}")
        finally:
            cap.release()


    @ia.route('/train', methods=['POST'])
    @check_role(['ADMINISTRADOR'])
    def train():
        message = {"correcto": '', "alerta": '', "error": ''}
        try:
            C_IA_Trainer.train_model()
            message['correcto'] = "Se ha entrenado correctamente, se ha generado un nuevo modelo de apredizaje con los nuevos datos que se recabaron"
        except Exception as e:
            message['error'] = str(e)
        return json.dumps(message)


    def train_model():
        directories = os.listdir('app/static/uploads/people_photo')
        X = []
        y = []

        for directory in directories:
            files = os.listdir(f'app/static/uploads/people_photo/{directory}')
            for file in files:
                img = cv2.imread(
                    f'app/static/uploads/people_photo/{directory}/{file}')

                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = cv2.resize(img, (64, 64))
                img = img.astype(np.float32) / 255.0
                img = img.reshape(-1, 64 * 64 * 3)
                X.append(img)

                y.append(directory)

        X = np.concatenate(X)
        y = np.array(y)

        custom_svm = CustomSVM()
        custom_svm.train(X, y)
        custom_svm.save_model('model_weights.joblib')


    @ia.route('/ia_trainer')
    @check_role(['ADMINISTRADOR'])
    def ia_trainer():
        form = F_Trainer()
        return render_template('v_ia_trainer.html', title="Entrenamiento de Modelo de IA", form=form)

    

app/controllers/C_Login.py
from flask import Blueprint, json, redirect, render_template, session, url_for

from app.forms.F_Login import F_Login
from app.models.Models import People, Roles, Users
from app.utils.utils import check_role
class C_Login():
    login = Blueprint('login',__name__)
    @login.route('/')
    def index():
        if 'logged' in session:
            return redirect(url_for('login.principal'))
        form = F_Login()
        return render_template('v_login.html', title='Login', form=form)
    
    @login.route('/process_user_credentials', methods=['POST'])
    def process_user_credentials():
        message = {"correcto": '', "alerta": '', "error": ''}
        form = F_Login()
        if form.validate_on_submit():
            usuario = form.txtUsuario.data
            contrasena = form.txtPassword.data
            user_data = Users.query.with_entities(Users.user_id.label('user_id'), Roles.role_desc.label('rol'), Users.user_password.label('user_password'), Users.user_state.label('user_state'), Users.user_peop_id).join(Roles, Roles.role_id == Users.user_role_id).filter(Users.user_name == usuario, Users.user_state == 'A').first()
            if user_data is not None:
                password_hash = user_data.user_password
                if Users.check_password_hash(password_hash,contrasena):
                    person_people = People.query.filter_by(peop_id = user_data.user_peop_id).first()
                    session['logged'] = True
                    session['user_id'] = user_data.user_id
                    session['habilitation'] = user_data.user_state
                    session['person'] = person_people.peop_names + ' ' + person_people.peop_lastnames
                    session['rol'] = user_data.rol
                    session['person_cod'] = user_data.user_peop_id  
                    message['correcto'] = "Se ha comprobado las credenciales"
                else:
                    message['error'] = "Usuario o contraseña incorrectas"
            else:
                message['error'] = "El usuario ingresado no existe o ha sido bloqueado"
        else:
            errores = {}
            for campo, errores_campo in form.errors.items():
                label = form[campo].label.text
                errores[campo] = '{}: {} <br>'.format(
                    label, ', '.join(errores_campo))
            message['error'] = {}
            message['error']['validacion'] = '<strong>Por favor, corrija los errores en el formulario.</strong><br>'
            message['error']['detalles'] = errores
        return json.dumps(message)
    
    @login.route('/principal')
    @check_role(['ADMINISTRADOR', 'MEDICO', 'FARMACEUTICO'])
    def principal():
        return render_template('v_principal.html', title="Bienvenido")

app/controllers/C_Pharma.py
from datetime import datetime
from flask import Blueprint, json, render_template, request, session
from app.forms.F_People import F_Busqueda_Persona

from app.forms.F_Pharma import F_Deliver_Medications
from app.models.Models import db, PeoplePrescriptionDetails
from app.utils.utils import check_role


class C_Pharma():
    pharma = Blueprint('pharma', __name__)
    
    @pharma.route('/medical_prescriptions')
    @check_role(['FARMACEUTICO'])
    def medical_prescriptions():
        form = F_Deliver_Medications()
        formBusq = F_Busqueda_Persona()
        return render_template('v_medical_prescriptions.html', title="Ver Prescripciones Médicas", form=form, formBusq=formBusq)
    
    @pharma.route('/deliver_medication', methods=['POST'])
    @check_role(['FARMACEUTICO'])
    def deliver_medication():
        message = {"correcto": '', "alerta": '', "error": '', 'delivered': []}
        deliver = request.form.getlist("txtMedicina")
        parcel_types = request.form.getlist("sltTipoEmpaque")
        quantity = request.form.getlist("txtCantMedicina")
        print(len(deliver))
        print(len(parcel_types))
        print(len(quantity))
        if len(deliver) > 0 and len(parcel_types) > 0 and len(quantity) > 0:
                for i, d in enumerate(deliver):
                    if int(quantity[i]) > 0:
                        prescription = PeoplePrescriptionDetails.query.filter_by(prde_id=d).first()
                        if prescription.prde_dispatched!='S':
                            prescription.prde_dispatched = "S"
                            prescription.prde_parcel_type_id = parcel_types[i]
                            prescription.prde_quantity = quantity[i]
                            prescription.prde_date_dispatched = datetime.now()
                            prescription.prde_user_dispatcher_id = session['user_id']
                            prescription.prde_user_updated_id = session['user_id']
                            db.session.commit()
                            message['delivered'].append(d)
                        else:
                            message['alerta'] = "Ya se ha entregado este medicamento"
                            return json.dumps(message)
                message["correcto"] = "Los medicamentos han sido entregados correctamente"
        else:
            message["alerta"] = "Debe seleccionar al menos un medicamento"
        return json.dumps(message)

app/controllers/C_Users.py
from datetime import date
from flask import Blueprint, json, render_template, request, session
from app.forms.F_People import F_Busqueda_Persona
from app.forms.F_Users import F_Cambio_Contrasena, F_Registro_Usuario
from app.models.Models import People, Roles, Users, db
from app.utils.utils import check_role


class C_Users():
    usuarios = Blueprint('usuarios', __name__)

    @usuarios.route('/users')
    @check_role(['ADMINISTRADOR'])
    def users():
        formBusq = F_Busqueda_Persona()
        formUser = F_Registro_Usuario()
        roles = Roles.query.order_by(Roles.role_desc).all()
        choices = [(rol.role_id, rol.role_desc) for rol in roles]
        formUser.sltRol.choices = choices
        return render_template('v_users.html', title="Listado de Usuarios", formBusq=formBusq, formUser=formUser, roles=roles)

    @usuarios.route('/register_user_data', methods=['POST'])
    @check_role(['ADMINISTRADOR'])
    def register_user_data():
        message = {"correcto": '', "alerta": '', "error": ''}
        form = F_Registro_Usuario(request.form)
        roles = Roles.query.order_by(Roles.role_desc).all()
        choices = [(rol.role_id, rol.role_desc) for rol in roles]
        form.sltRol.choices = choices
        if form.validate_on_submit():
            persona = form.txtPersonaCod.data
            contrasena = form.txtPassword.data
            rol = form.sltRol.data
            estado = form.sltEstado.data
            user = Users.query.filter_by(user_peop_id=form.txtPersonaCod.data).first()
            person_data = People.query.filter_by(peop_id = persona).first()
            if user is not None:
                # Actualizar los datos del usuario
                if contrasena!="":
                    user.user_password = Users.hash_password(contrasena)
                user.user_name = person_data.peop_dni
                user.user_role_id = rol
                user.user_updated_id = session['user_id']
                user.user_state = estado
                db.session.commit()
            else:
                # Registrar el usuario nuevo
                user = Users()
                user.user_peop_id = persona
                user.user_name = person_data.peop_dni
                if contrasena!="":
                    user.user_password = Users.hash_password(contrasena)
                user.user_role_id = rol
                user.user_created_id = session['user_id']
                user.user_state = estado
                db.session.add(user)
                db.session.commit()
            message['correcto'] = '<strong>Se ha realizado correctamente el registro de los datos del usuario</strong>'
        else:
            errores = {}
            for campo, errores_campo in form.errors.items():
                label = form[campo].label.text
                errores[campo] = '{}: {} <br>'.format(
                    label, ', '.join(errores_campo))
            message['error'] = {}
            message['error']['validacion'] = '<strong>Por favor, corrija los errores en el formulario.</strong><br>'
            message['error']['detalles'] = errores
        return json.dumps(message)
    
    @usuarios.route('/get_users_list', methods=['GET'])
    @check_role(['ADMINISTRADOR'])
    def get_users_list():
        message = {"correcto": '', "alerta": '', "error": ''}
        users = Users.query.with_entities(Users.user_id.label("id"), Users.user_name.label("username"), (People.peop_names + ' ' + People.peop_lastnames).label("person"), Users.user_peop_id.label("peop_id"), Users.user_state.label("state"), Roles.role_id.label("role_id"), Roles.role_desc.label("role")).join(People, People.peop_id == Users.user_peop_id, isouter=True).join(Roles, Roles.role_id == Users.user_role_id).paginate(
            page=request.args.get('page', 1), per_page=10)
        return {
            'data': 
            [
                {
                    "id": user.id,
                    "username": user.username,
                    "person": user.person,
                    "person_id": user.peop_id,
                    "state": user.state,
                    "state_full": "ACTIVO" if user.state == "A" else "INACTIVO",
                    "role_desc": user.role,
                    "role_id": user.role_id,
                } for user in users
            ] ,
            'total': users.total
        }
    
    @usuarios.route('/password_change')
    def password_change():
        form = F_Cambio_Contrasena()
        return render_template('v_password_change.html', form=form, title="Cambio de Contraseña")

    @usuarios.route('/change_password', methods=['POST'])
    def change_password():
        message = {"correcto": '', "alerta": '', "error": ''}
        form = F_Cambio_Contrasena(request.form)
        if form.validate_on_submit:
            old_password = form.txtOldPassword.data
            new_password = form.txtNewPassword.data
            user = Users.query.filter_by(user_id=session['user_id']).first()
            if user is not None:
                if Users.check_password_hash(user.user_password, old_password):
                    user.user_password = Users.hash_password(new_password)
                    db.session.commit()
                    message['correcto'] = '<strong>Se ha realizado correctamente el cambio de contraseña</strong>'
                else:
                    message['alerta'] = '<strong>La contraseña actual no es correcta</strong>'
            else:
                message['alerta'] = '<strong>El usuario no existe</strong>'
        return json.dumps(message)
    
    @usuarios.route('/delete_user/<user>', methods=['DELETE'])
    def delete_user(user):
        message = {"correcto": '', "alerta": '', "error": ''}
        user = Users.query.filter(Users.user_id == user).first()
        if user:
            db.session.delete(user)
            db.session.commit()
            message['correcto'] = 'Se ha eliminado correctamente al Usuario'
        else:
            message['error'] = 'Usuario no encontrado'
        return json.dumps(message)

app/templates/r_proof_delivery.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Constancia de Entrega</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <h2>Constancia de Entrega de Medicamentos</h2>
    <p>El/la farmaceutico(a) {{ session['person'] }}, deja constancia de haber entregado satifactoriamente los
        medicamentos más abajo declarados al paciente <b>{{ datos_persona.peop_names+' '+datos_persona.peop_lastnames
            }}</b> en fecha {{ datos[0].prde_date_dispatched.strftime('%d/%m/%Y') }}</p>

    <table>
        <thead>
            <tr>
                <th>Medicamento</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for m in datos %}
            <tr>
                <td>{{ m.prde_medicine.upper() }}</td>
                <td>{{ m.prde_quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Total Entregados:</th>
                <th>{{ datos[0].total_quantity }}</th>
            </tr>
        </tfoot>
    </table>

    <p>A continuación el paciente deja constancia de su conformidad con la entrega, presentando firma ológrafa del
        mismo.</p>
    <p>{{ datos_persona.peop_names+' '+datos_persona.peop_lastnames }}<br>{{ datos_persona.peop_dni }}</p>
</body>

</html>

app/templates/v_ia_trainer.html
{% extends 'v_master.html' %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ title }}</h4>
                <div class="row">
                    {{ form.honeypot }}
                    {{ form.hidden_tag() }}
                    <div class="col-md-6">
                        <div class="d-grid gap-2">
                            <button type="button" name="btnEntrenarIA" id="btnEntrenarIA" class="btn btn-primary">
                                Entrenar IA
                            </button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-grid gap-2">
                            <button type="button" name="btnPruebaIdentificación" id="btnPruebaIdentificación"
                                class="btn btn-primary">
                                Prueba de Identificación
                            </button>
                        </div>
                    </div>
                </div>
                <!-- <img src="{{ url_for('video_feed') }}" alt="Webcam Stream"> -->
            </div>
        </div>

    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    var csrfToken = document.querySelector("[name='csrf_token']").value;
        axios.defaults.headers.common['X-CSRFToken'] = csrfToken;
    var btnEntrenarIA = document.querySelector("#btnEntrenarIA");
    btnEntrenarIA.addEventListener('click', (e)=>{
        e.preventDefault();
        axios.post("{{ url_for('ia.train' ) }}", {TRAIN:"ENTRENAMIENTO"}, axiosConfig())
        .then(function (response) {
            var r = response.data;
            generarMensajeCorrecto(r);
        })
        .catch(function (error) {
            console.log(error);
        })
    });
    var btnPruebaIdentificación = document.querySelector("#btnPruebaIdentificación");
        btnPruebaIdentificación.addEventListener('click', (e) => {
            e.preventDefault();
            axios.post("{{ url_for('ia.identify' ) }}", { TRAIN: "IDENTIFY" }, axiosConfig())
                .then(function (response) {
                    var r = response.data;
                    if (r['correcto']!="") {
                        generarMensajeCorrecto(r);
                    } else {
                        generarMensajeAlerta(r);
                    }
                })
                .catch(function (error) {
                    console.log(error);
                })
        });
</script>
{% endblock %}

app/templates/v_login.html
{% extends 'v_master.html' %}
{% block login %}
<style>
    .login-form {
        padding-top: 20%;
    }

    .card-body {
        border: 1px solid transparent;
        border-radius: 5px;
        background-color: white;
    }

    img.img-fluid {
        width: 100%;
        object-fit: cover;
    }

    #bodyLogin {
        margin-top: 5vh;
    }

    @media (max-width: 768px) {
        #bodyLogin {
            margin-top: -80px;
        }
        .login-form {
        padding-top: 50px;
    }
    }
</style>

<div class="row" id="bodyLogin">
    <div class="col-md-6 offset-md-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <img class="img-fluid" src="{{ url_for('static', filename='img/fondo2.png') }}" alt="">
                </div>
                <div class="col-md-6">
                    <form id="frmLogin" novalidate>
                        <div class="container col-md-11 login-form">
                            {% if error %}
                            <div class="alert alert-danger">{{ error }}</div>
                            {% endif %}
                            <h4 class="text-center">Ingrese sus credenciales</h4>
                            <div class="form-floating mb-3">
                                {{ form.txtUsuario(class="form-control", placeholder="Ingrese su usuario") }}
                                <label for="txtUsuario">Usuario</label>
                            </div>
                            <div class="form-floating mb-3">
                                {{ form.txtPassword(class="form-control", placeholder="Ingrese su usuario") }}
                                <label for="txtPassword">Contraseña</label>
                            </div>
                            {{ form.hidden_tag() }}
                            <div class="d-grid gap-2 mb-3">
                                <button type="submit" class="btn btn-primary btn-lg">Ingresar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
    <script>
        axios.defaults.headers.common['X-CSRFToken'] = csrfToken;
        var frmLogin = document.querySelector("#frmLogin");
        frmLogin.addEventListener('submit', (e)=>{
            e.preventDefault();
            var formData = new FormData(frmLogin);
            axios.post("{{ url_for('login.process_user_credentials' ) }}", formData)
            .then(function (response) {
                var mensajes = response.data;
                if (mensajes['correcto'] != '') {
                    window.location.href = "{{ url_for('login.principal' ) }}";
                }
                if (mensajes['error'] != '') {
                    generarMensajeError(mensajes);
                }

            })
            .catch(function (error) {
                error
            })
        });
    </script>
{% endblock %}

app/templates/v_principal.html
{% extends 'v_master.html' %}
{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Bienvenido, {{ session['person'] }}</h4>
                <p class="card-text">Que desea hacer:</p>
                <div class="row">
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('people.people' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-info">
                                    <i class="fas fa-person fa-5x  "></i>
                                    <p>Personas</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('usuarios.users' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-info">
                                    <i class="fa fa-users fa-5x" aria-hidden="true"></i>
                                    <p>Usuarios</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('ia.ia_trainer' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-info">
                                    <i class="fa fa-robot fa-5x" aria-hidden="true"></i>
                                    <p>Entrenamiento de IA</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('doctors.medical_consultations' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-dark">
                                    <i class="fa fa-stethoscope fa-5x" aria-hidden="true"></i>
                                    <p>Consulta Médica</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('doctors.doctors_register' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-dark">
                                    <i class="fa fa-user-md fa-5x" aria-hidden="true"></i>
                                    <p>Registro de Médicos</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('pharma.medical_prescriptions' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-dark">
                                    <i class="fa fa-prescription-bottle-alt fa-5x" aria-hidden="true"></i>
                                    <p>Prescripciones Médicas</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('usuarios.password_change' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-success">
                                    <i class="fa fa-lock fa-5x" aria-hidden="true"></i>
                                    <p>Cambio de Contraseña</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('maint.maintenance' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-success">
                                    <i class="fa fa-tools fa-5x" aria-hidden="true"></i>
                                    <p>Mantenimiento</p>
                                </button>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mb-3">
                        <a href="{{ url_for('report.statistics' ) }}" style="text-decoration:none;">
                            <div class="d-grid gap-2">
                                <button type="button" name="" id="" class="btn btn-outline-success">
                                    <i class="fa fa-pie-chart fa-5x" aria-hidden="true"></i>
                                    <p>Estadística y Reportes</p>
                                </button>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}